lib/linkhut_web/router.ex
defmodule LinkhutWeb.Router do
  use LinkhutWeb, :router
  import Phoenix.LiveDashboard.Router

  import LinkhutWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :put_root_layout, html: {LinkhutWeb.Layouts, :root}
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug LinkhutWeb.Plugs.GlobalAssigns
  end

  pipeline :token_auth do
    plug LinkhutWeb.Plugs.VerifyTokenAuth

    plug ExOauth2Provider.Plug.EnsureAuthenticated,
      otp_app: :linkhut,
      handler: LinkhutWeb.Plugs.AuthErrorHandler
  end

  pipeline :feed do
    plug :fetch_session
    plug :accepts, ["xml"]
    plug LinkhutWeb.Plugs.VerifyTokenAuth
  end

  pipeline :api do
    plug :accepts, ["xml", "json"]
  end

  pipeline :admin do
    plug LinkhutWeb.Plugs.EnsureRole, :admin
  end

  pipeline :ifttt do
    plug LinkhutWeb.Plugs.VerifyIFTTTHeader
  end

  pipeline :snapshot_serve do
    plug :accepts, ["html"]
    plug :put_secure_browser_headers
  end

  scope "/_/v1/oauth", LinkhutWeb.Api.OAuth, as: :oauth do
    pipe_through :api

    post "/token", TokenController, :create
    post "/revoke", TokenController, :revoke
  end

  scope "/_/v1/", LinkhutWeb.Api, as: :api do
    pipe_through [:api, :token_auth]

    get "/posts/update", PostsController, :update
    get "/posts/add", PostsController, :add
    get "/posts/delete", PostsController, :delete
    get "/posts/get", PostsController, :get
    get "/posts/recent", PostsController, :recent
    get "/posts/dates", PostsController, :dates
    get "/posts/all", PostsController, :all
    get "/posts/suggest", PostsController, :suggest

    get "/tags/get", TagsController, :get
    get "/tags/delete", TagsController, :delete
    get "/tags/rename", TagsController, :rename
  end

  scope "/_/ifttt/v1/", LinkhutWeb.Api.IFTTT, as: :ifttt do
    pipe_through [:api, :ifttt]

    get "/status", StatusController, :ok
    post "/test/setup", TestController, :setup
  end

  scope "/_/ifttt/v1/", LinkhutWeb.Api.IFTTT, as: :ifttt do
    pipe_through [:api, :token_auth]

    get "/user/info", UserController, :info

    post "/triggers/new_public_link", TriggersController, :new_public_link
    post "/triggers/new_public_link_tagged", TriggersController, :new_public_link_tagged

    post "/actions/add_public_link", ActionsController, :add_public_link
    post "/actions/add_private_link", ActionsController, :add_private_link
  end

  scope "/_/feed/unread", LinkhutWeb, as: :feed do
    pipe_through [:feed, :token_auth]

    get "/", LinkController, :unread, as: :unread
    get "/*tags", LinkController, :unread, as: :unread
  end

  scope "/_/feed", LinkhutWeb, as: :feed do
    pipe_through :feed

    get "/", LinkController, :show
    get "/~:username", LinkController, :show, as: :user
    get "/~:username/-:url", LinkController, :show, as: :user_bookmark
    get "/~:username/-:url/*tags", LinkController, :show, as: :user_bookmark_tags
    get "/~:username/*tags", LinkController, :show, as: :user_tags
    get "/-:url", LinkController, :show, as: :bookmark
    get "/-:url/*tags", LinkController, :show, as: :bookmark_tags
    get "/*tags", LinkController, :show, as: :tags
  end

  scope "/_", LinkhutWeb.Settings do
    pipe_through [:browser, :require_authenticated_user]

    get "/import", ImportController, :show
    get "/import/:task", ImportController, :status
    get "/export", ImportController, :show
    post "/import", ImportController, :upload

    get "/download", ExportController, :download

    get "/misc", MiscController, :show
    get "/profile", ProfileController, :show
    put "/profile", ProfileController, :update
    put "/profile/delete", ProfileController, :delete

    get "/security", SecurityController, :show
  end

  scope "/_", LinkhutWeb.Settings do
    pipe_through [:browser, :require_sudo_mode]

    get "/profile/delete", ProfileController, :remove
  end

  # Snapshot file serving (token-authenticated, no session required)
  scope "/_", LinkhutWeb do
    pipe_through [:snapshot_serve]
    get "/snapshot/:token/serve", SnapshotController, :serve
  end

  scope "/_", LinkhutWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/add", LinkController, :new
    post "/add", LinkController, :insert

    get "/edit", LinkController, :edit
    put "/edit", LinkController, :update

    get "/delete", LinkController, :remove
    put "/delete", LinkController, :delete

    # Archive routes (link-scoped, type-based)
    get "/archive/:link_id", SnapshotController, :show
    get "/archive/:link_id/type/:type", SnapshotController, :show, as: :archive_type
    get "/archive/:link_id/type/:type/full", SnapshotController, :full
    get "/archive/:link_id/type/:type/download", SnapshotController, :download
    get "/archive/:link_id/all", SnapshotController, :index
    post "/archive/:link_id/recrawl", SnapshotController, :recrawl

    delete "/logout", Auth.SessionController, :delete
  end

  scope "/_/oauth", LinkhutWeb.Settings do
    pipe_through [:browser, :require_authenticated_user]

    get "/", OauthController, :show
    get "/personal-token", OauthController, :new_personal_token
    post "/personal-token", OauthController, :create_personal_token
    get "/personal-token/revoke/:id", OauthController, :revoke_token
    put "/personal-token/revoke/:id", OauthController, :revoke_token

    get "/register", OauthController, :new_application
    post "/register", OauthController, :create_application
    get "/registered", OauthController, :show_application
    get "/application/:uid/settings", OauthController, :edit_application
    put "/application/:uid/settings", OauthController, :update_application
    post "/application/delete/:uid", OauthController, :delete_application
    post "/revoke-tokens/:uid", OauthController, :revoke_application
    post "/reset-secret/:uid", OauthController, :reset_application
    post "/revoke-access/:uid", OauthController, :revoke_access

    get "/authorize", OauthController, :new_authorization
    post "/authorize", OauthController, :create_authorization
    delete "/authorize", OauthController, :delete_authorization
  end

  scope "/_/", LinkhutWeb.Auth do
    pipe_through [:browser, :require_authenticated_user]

    post "/confirm", ConfirmationController, :create
    get "/confirm/:token", ConfirmationController, :update
    get "/confirm-email/:token", ConfirmationController, :confirm_email
  end

  scope "/_/admin" do
    pipe_through [:browser, :admin]
    get "/", LinkhutWeb.Settings.AdminController, :show
    post "/ban", LinkhutWeb.Settings.AdminController, :ban
    post "/unban", LinkhutWeb.Settings.AdminController, :unban
    post "/recompute_storage", LinkhutWeb.Settings.AdminController, :recompute_storage

    live_dashboard "/dashboard",
      metrics: LinkhutWeb.Telemetry,
      ecto_repos: [Linkhut.Repo],
      ecto_psql_extras_options: [long_running_queries: [threshold: "200 milliseconds"]],
      metrics_history: {LinkhutWeb.MetricsStorage, :metrics_history, []}
  end

  # Enable Swoosh mailbox preview in development
  if Application.compile_env(:linkhut, :dev_routes) do
    scope "/_" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  scope "/_", LinkhutWeb do
    pipe_through :browser

    get "/register", Auth.RegistrationController, :new
    post "/register", Auth.RegistrationController, :create

    get "/login", Auth.SessionController, :new
    post "/login", Auth.SessionController, :create

    get "/reset-password", Auth.ResetPasswordController, :new
    post "/reset-password", Auth.ResetPasswordController, :create
    get "/reset-password/:token", Auth.ResetPasswordController, :edit
    put "/reset-password/:token", Auth.ResetPasswordController, :update
  end

  scope "/_/unread", LinkhutWeb do
    pipe_through [:browser, :require_authenticated_user]
    get "/", LinkController, :unread, as: :unread
    get "/*tags", LinkController, :unread, as: :unread
  end

  scope "/", LinkhutWeb do
    pipe_through :browser

    get "/", LinkController, :show
    get "/~:username", LinkController, :show, as: :user
    get "/~:username/-:url", LinkController, :show, as: :user_bookmark
    get "/~:username/-:url/*tags", LinkController, :show, as: :user_bookmark_tags
    get "/~:username/*tags", LinkController, :show, as: :user_tags
    get "/-:url", LinkController, :show, as: :bookmark
    get "/-:url/*tags", LinkController, :show, as: :bookmark_tags
    get "/*tags", LinkController, :show, as: :tags
  end
end

lib/linkhut/links/public_link.ex
defmodule Linkhut.Links.PublicLink do
  @moduledoc false

  use Ecto.Schema
  alias Linkhut.Accounts.User

  @type t :: Ecto.Schema.t()

  @primary_key false
  schema "public_links" do
    field :id, :integer, primary_key: true
    field :inserted_at, :utc_datetime
    belongs_to :user, User, define_field: false
    field :saves, :integer
    field :rank, :float
    field :user_daily_entry, :integer
  end
end

lib/linkhut_web/controllers/link_controller.ex
defmodule LinkhutWeb.LinkController do
  use LinkhutWeb, :controller

  alias Linkhut.Accounts
  alias Linkhut.Links
  alias Linkhut.Links.Link
  alias Linkhut.Pagination
  alias Linkhut.Search
  alias Linkhut.Search.Context
  alias Linkhut.Tags
  alias LinkhutWeb.Breadcrumb
  alias LinkhutWeb.Controllers.Utils

  @links_per_page 20

  def new(conn, params) do
    conn
    |> render("add.html",
      changeset: Links.change_link(%Link{}, Map.take(params, ["url", "title", "tags", "notes"]))
    )
  end

  def insert(conn, %{"link" => link_params}) do
    user = conn.assigns[:current_user]

    case Links.create_link(user, link_params) do
      {:ok, link} ->
        conn
        |> put_flash(:info, "Added link: #{link.url}")
        |> redirect(to: Routes.user_path(conn, :show, user.username))

      {:error, changeset} ->
        conn
        |> render("add.html", changeset: changeset)
    end
  end

  def edit(conn, %{"url" => url}) do
    user = conn.assigns[:current_user]
    link = Links.get(url, user.id)

    if link != nil do
      conn
      |> render("edit.html", changeset: Links.change_link(link))
    else
      conn
      |> put_flash(:error, "Couldn't find link for #{url}")
      |> redirect(to: Routes.link_path(conn, :show))
    end
  end

  def update(conn, %{"link" => %{"url" => url} = link_params}) do
    user = conn.assigns[:current_user]
    link = Links.get(url, user.id)

    case Links.update_link(link, link_params) do
      {:ok, link} ->
        conn
        |> put_flash(:info, "Saved link: #{link.url}")
        |> redirect(to: Routes.user_path(conn, :show, user.username))

      {:error, changeset} ->
        conn
        |> render("edit.html", changeset: changeset)
    end
  end

  def remove(conn, %{"url" => url}) do
    user = conn.assigns[:current_user]
    link = Links.get(url, user.id)

    if link != nil do
      conn
      |> render("delete.html", link: link, changeset: Links.change_link(link))
    else
      conn
      |> put_flash(:error, "Couldn't find link for #{url}")
      |> redirect(to: Routes.link_path(conn, :show))
    end
  end

  def delete(conn, %{"link" => %{"url" => url, "are_you_sure?" => confirmed}}) do
    user = conn.assigns[:current_user]
    link = Links.get(url, user.id)

    if confirmed == "true" do
      case Links.delete_link(link) do
        {:ok, link} ->
          conn
          |> put_flash(:info, "Deleted link: #{link.url}")
          |> redirect(to: Routes.user_path(conn, :show, user.username))

        {:error, changeset} ->
          conn
          |> render("delete.html", changeset: changeset)
      end
    else
      conn
      |> put_flash(:error, "Please confirm you want to delete this link")
      |> redirect(to: Routes.link_path(conn, :remove, url: url))
    end
  end

  defp has_query?(%{"query" => _}), do: true
  defp has_query?(_), do: false

  defp has_filters?(%{"username" => _}), do: true
  defp has_filters?(%{"tags" => _}), do: true
  defp has_filters?(%{"url" => _}), do: true
  defp has_filters?(_), do: false

  def show(conn, params) do
    tag_options = Utils.Tags.parse_options(params)

    cond do
      has_query?(params) ->
        query(conn, context(params), Map.get(params, "query"), page(params), tag_options)

      has_filters?(params) ->
        filter(conn, context(params), page(params), tag_options)

      true ->
        explore(conn, view(params), page(params), tag_options)
    end
  end

  def unread(conn, params) do
    user = conn.assigns[:current_user]
    page = page(params)
    query = Map.get(params, "query", "")

    context = %{context(params) | from: user, visible_as: user.username}

    links_query =
      Search.search(
        context,
        query,
        Keyword.put(query_opts(conn), :is_unread, true)
      )

    conn
    |> render(:index,
      links: realize_query(links_query, page),
      tags: Tags.for_query(links_query, Utils.Tags.parse_options(params)),
      query: query,
      context: context,
      breadcrumb: Breadcrumb.from_context(context, title: :unread),
      scope: Utils.scope(conn)
    )
  end

  defp query_opts(%Plug.Conn{query_params: query_params} = conn) do
    order =
      case query_params do
        %{"order" => "asc"} -> :asc
        %{"order" => "desc"} -> :desc
        _ -> nil
      end

    sort_by =
      case query_params do
        %{"sort" => "recency"} -> :recency
        %{"sort" => "popularity"} -> :popularity
        %{"sort" => "relevancy"} -> :relevancy
        %{"query" => query} when is_binary(query) and query != "" -> :relevancy
        _ -> nil
      end

    opts =
      case {sort_by, order} do
        {nil, nil} -> []
        {nil, order} -> [order: order]
        {sort_by, nil} -> [sort_by: sort_by]
        {sort_by, order} -> [sort_by: sort_by, order: order]
      end

    case conn.assigns[:current_user] do
      %{id: user_id} -> Keyword.put(opts, :current_user_id, user_id)
      _ -> opts
    end
  end

  defp explore(conn, view, page, tag_options) do
    context =
      case conn.assigns[:current_user] do
        nil -> %Context{}
        current_user -> %Context{visible_as: current_user.username}
      end

    links_query =
      case view do
        :recent -> Links.recent(query_opts(conn))
        :popular -> Links.popular(query_opts(conn))
      end

    conn
    |> render(:index,
      links: realize_query(links_query, page),
      tags: Tags.for_query(links_query, tag_options),
      query: "",
      context: context,
      breadcrumb: Breadcrumb.from_context(context, title: view),
      scope: Utils.scope(conn)
    )
  end

  defp query(conn, context, query, page, tag_options) do
    context =
      case conn.assigns[:current_user] do
        nil -> context
        current_user -> %Context{context | visible_as: current_user.username}
      end

    links_query = Search.search(context, query, query_opts(conn))

    conn
    |> render(:index,
      links: realize_query(links_query, page),
      tags: Tags.for_query(links_query, tag_options),
      query: query,
      context: context,
      breadcrumb: Breadcrumb.from_context(context),
      scope: Utils.scope(conn)
    )
  end

  defp filter(conn, %Context{} = context, page, tag_options) do
    context =
      case conn.assigns[:current_user] do
        nil -> context
        current_user -> %Context{context | visible_as: current_user.username}
      end

    links_query = Search.search(context, "", query_opts(conn))

    conn
    |> render(:index,
      links: realize_query(links_query, page),
      tags: Tags.for_query(links_query, tag_options),
      query: "",
      context: context,
      breadcrumb: Breadcrumb.from_context(context),
      scope: Utils.scope(conn)
    )
  end

  defp realize_query(query, page) do
    query
    |> Pagination.page(page, per_page: @links_per_page)
    |> Map.update!(
      :entries,
      &Enum.chunk_by(&1, fn link -> DateTime.to_date(link.inserted_at) end)
    )
  end

  defp context(%{"username" => username, "tags" => tags, "url" => url}) do
    %Context{
      from: Accounts.get_user!(username),
      tagged_with: Enum.uniq_by(tags, &String.downcase(&1)) |> Enum.map(&URI.decode/1),
      url: URI.decode(url)
    }
  end

  defp context(%{"username" => username, "tags" => tags}) do
    %Context{
      from: Accounts.get_user!(username),
      tagged_with: Enum.uniq_by(tags, &String.downcase(&1)) |> Enum.map(&URI.decode/1)
    }
  end

  defp context(%{"username" => username, "url" => url}) do
    %Context{
      from: Accounts.get_user!(username),
      url: URI.decode(url)
    }
  end

  defp context(%{"tags" => tags, "url" => url}) do
    %Context{
      tagged_with: Enum.uniq_by(tags, &String.downcase/1) |> Enum.map(&URI.decode/1),
      url: URI.decode(url)
    }
  end

  defp context(%{"tags" => tags}),
    do: %Context{
      tagged_with: Enum.uniq_by(tags, &String.downcase/1) |> Enum.map(&URI.decode/1)
    }

  defp context(%{"username" => username}), do: %Context{from: Accounts.get_user!(username)}
  defp context(%{"url" => url}), do: %Context{url: URI.decode(url)}
  defp context(_), do: %Context{}

  defp page(%{"p" => page}), do: page
  defp page(_), do: 1

  defp view(%{"v" => "recent"}), do: :recent
  defp view(%{"v" => "popular"}), do: :popular
  defp view(_), do: :recent
end

lib/linkhut_web/templates/link/_bookmark.html.heex
<div class="bookmark-card">
  <div class="bookmark">
    <div data-posted-on={@link.inserted_at} data-saves={@link.saves} data-relevance={@link.score} class="title">
      <h4><a rel="nofollow" class="taggedlink" href={@link.url}>{@link.title}</a></h4>
      <%= if @link.is_private do %>
        <span class="no-css-label">{gettext("Private")}</span>
      <% end %>
      <%= if @context.url == nil and not (@link.is_private or @link.is_unread) and @link.saves > 1 do %>
        <a class="savers" data-count={@link.saves} data-label={gettext("people")} href={html_path(@scope, url: @link.url)}></a>
      <% end %>
    </div>
    <div class="full-url">
      <a rel="nofollow" href={@link.url}>{@link.url}</a>
    </div>
    <div class="description">
      <%= if @logged_in? && @link.user_id == @current_user.id do %>
        {sanitize(HtmlSanitizeEx.basic_html(Earmark.as_html!(@link.notes, pure_links: false)))}
      <% else %>
        {sanitize(@link.notes_html)}
      <% end %>
    </div>
    <div class="ownership">
      <%= unless @logged_in? && @link.user_id == @current_user.id do %>
        <span>
          {gettext("by")} <a href={html_path(@scope, user: @link.user.username)}>{@link.user.username}</a>
        </span>
      <% end %>
      <span>
        {Timex.format!(@link.inserted_at, "{relative}", :relative)}
      </span>
      <%= if @context.url == nil and not (@link.is_private) and @link.saves > 1 do %>
        <span class="savers">
          {gettext("saved")} <a href={html_path(@scope, url: @link.url)}>{@link.saves}</a> {ngettext("time", "times", @link.saves)}
        </span>
      <% end %>
    </div>
    <div class="meta">
      <.link_tags scope={@scope} link={@link} />
      <%= if @logged_in? do %>
        <div class="actions">
          <h5 class="label">{gettext("Actions:")}</h5>
          <ul class="actions">
            <%= if !assigns[:hide_actions] do %>
              <%= if @link.user_id == @current_user.id do %>
                <li>
                  <a href={Routes.link_path(@conn, :edit, url: @link.url)}>{gettext("edit")}</a>
                </li>
                <li>
                  <a href={Routes.link_path(@conn, :delete, url: @link.url)}>{gettext("delete")}</a>
                </li>
                <%= if @link.is_unread do %>
                  <li>
                    <%= form_for :mark_as_read, Routes.link_path(@conn, :update), [method: :put], fn _ -> %>
                      {hidden_input(:link, :url, value: @link.url)}
                      {hidden_input(:link, :is_unread, value: false)}
                      {submit(gettext("mark as read"))}
                    <% end %>
                  </li>
                <% end %>
                <%= if @archiving_enabled? && @link.has_archive? do %>
                  <li>
                    <a href={~p"/_/archive/#{@link.id}"}>{gettext("view archive")}</a>
                  </li>
                <% end %>
              <% else %>
                <li>
                  <a href={Routes.link_path(@conn, :new, url: @link.url, title: @link.title, notes: @link.notes, tags: @link.tags)}>{gettext("copy to mine")}</a>
                </li>
              <% end %>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
  <%= if @link.is_private or @link.is_unread do %>
    <div class="icons">
      <%= if @link.is_private do %>
        <span data-icon-type="private" title={gettext("private")}></span>
      <% end %>
      <%= if @link.is_unread do %>
        <span data-icon-type="unread" title={gettext("unread")}></span>
      <% end %>
    </div>
  <% end %>
</div>
<hr />

lib/linkhut_web/templates/link/_controls.html.heex
<div id="controls">
  <section>
    <fieldset>
      <form id="searchform" action={@conn.request_path} method="get">
        <input id="query" type="text" name="query" value={assigns[:query]} size="45" placeholder="Search for bookmarks..." />
      </form>
    </fieldset>
  </section>
  <aside :if={@logged_in?}>
    <div class="actions">
      <a class="button primary" href={Routes.link_path(@conn, :new)}><span>{gettext("Add a bookmark")}</span></a>
    </div>
  </aside>
</div>

lib/linkhut_web/templates/link/_pagination.html.heex
<div class="pagination">
  <a :if={@page.has_prev} href={html_path(@scope, page: @page.prev_page)}>
    <span>❮</span>
    <span class="no-css-label">{gettext("Previous")}</span>
  </a>
  <%= cond do %>
    <% @page.num_pages <= 1 -> %>
    <% @page.num_pages <= 7 -> %>
      <a :for={p <- 1..@page.num_pages} class={if p == @page.page, do: "active"} href={html_path(@scope, page: p)}>
        <span>{p}</span>
      </a>
    <% @page.page < 3 or @page.page > @page.num_pages - 2 -> %>
      <a :for={p <- 1..3} class={if p == @page.page, do: "active"} href={html_path(@scope, page: p)}>
        <span>{p}</span>
      </a>
      <span>
        <span>&hellip;</span>
      </span>
      <a :for={p <- (@page.num_pages - 2)..@page.num_pages} class={if p == @page.page, do: "active"} href={html_path(@scope, page: p)}>
        <span>{p}</span>
      </a>
    <% @page.page == 3 -> %>
      <a :for={p <- 1..4} class={if p == @page.page, do: "active"} href={html_path(@scope, page: p)}>
        <span>{p}</span>
      </a>
      <span>
        <span>&hellip;</span>
      </span>
      <a :for={p <- (@page.num_pages - 1)..@page.num_pages} href={html_path(@scope, page: p)}>
        <span>{p}</span>
      </a>
    <% @page.page == @page.num_pages - 2 -> %>
      <a :for={p <- 1..2} href={html_path(@scope, page: p)}>
        <span>{p}</span>
      </a>
      <span>
        <span>&hellip;</span>
      </span>
      <a :for={p <- (@page.num_pages - 3)..@page.num_pages} class={if p == @page.page, do: "active"} href={html_path(@scope, page: p)}>
        <span>{p}</span>
      </a>
    <% true -> %>
      <a href={html_path(@scope, page: 1)}>
        <span>1</span>
      </a>
      <span>
        <span>&hellip;</span>
      </span>
      <a :for={p <- (@page.page - 1)..(@page.page + 1)} class={if p == @page.page, do: "active"} href={html_path(@scope, page: p)}>
        <span>{p}</span>
      </a>
      <span>
        <span>&hellip;</span>
      </span>
      <a href={html_path(@scope, page: @page.num_pages)}>
        <span>{@page.num_pages}</span>
      </a>
  <% end %>
  <a :if={@page.has_next} href={html_path(@scope, page: @page.next_page)}>
    <span class="no-css-label">{gettext("Next")}</span>
    <span>❯</span>
  </a>
</div>

lib/linkhut_web/templates/link/_side-pannel.html.heex
<aside>
  <%= if Context.is_user?(@context) && @context.from.bio != nil do %>
    <section>
      <h5><%= gettext("%{name}'s bio", name: @context.from.username) %></h5>
      <%= sanitize(Earmark.as_html!(@context.from.bio)) %>
    </section>
  <% end %>
  <%= if length(@tags) > 0 do %>
    <section>
      <h5><%= gettext("Tags") %></h5>
      <ul class="tag-cloud">
        <%= for %{tag: tag, count: count} <- @tags do %>
          <li><a href={current_path(@conn, tag: tag)} data-count={count}><%= tag %></a></li>
        <% end %>
      </ul>
    </section>
  <% end %>
  <section>
    <div class="explore">
      <h5><%= gettext("Explore") %></h5>
      <ul>
        <li><a href={Routes.link_path(@conn, :show, v: "recent")}><%= gettext("Recent") %></a></li>
        <li><a href={Routes.link_path(@conn, :show, v: "popular")}><%= gettext("Popular") %></a></li>
      </ul>
    </div>
  </section>
  <section>
    <h5>
      <a class="feed-link" href={feed_path(@conn)}><%= gettext("RSS feed") %></a>
    </h5>
  </section>
</aside>

lib/linkhut_web/templates/link/_user-info.html.eex
<aside>
    <%= if length(@tags) > 0 do %>
        <section>
            <h5><%= gettext "%{name}'s tags", name: @user.username %></h5>
            <ul class="tag-cloud">
                <%= for [tag, _count] <- @tags do %>
                <li><a href="<%= "#{@conn.request_path}/#{tag}" %>"><%= tag %></a></li>
                <% end %>
            </ul>
        </section>
    <% end %>
    <%= if @user.bio != nil do %>
        <section>
            <h5><%= gettext "%{name}'s bio", name: @user.username %></h5>
            <%= sanitize(Earmark.as_html!(@user.bio)) %>
        </section>
    <% end %>
    <section>
        <h5>
        <a class="feed-link" href="<%= Routes.feed_link_url(@conn, :show, @user.username)%>">
            <svg data-icon="rss-feed" width="16" height="16" viewBox="0 0 256 256">
                <circle cx="68" cy="189" r="24" />
                <path d="M160 213h-34a82 82 0 0 0 -82 -82v-34a116 116 0 0 1 116 116z" />
                <path d="M184 213A140 140 0 0 0 44 73 V 38a175 175 0 0 1 175 175z" />
            </svg><%= gettext "RSS feed" %>
        </a>
        </h5>
    </section>
</aside>

lib/linkhut_web/templates/link/add.html.heex
<div>
  <h3>Save a new link</h3>
  <%= form_for @changeset, Routes.link_path(@conn, :insert), fn f -> %>
    <fieldset>
      {input(f, :url)}
      {input(f, :title)}
      {input(f, :notes, type: :textarea, maxlength: 1024)}
      {input(f, :tags)}
      <div class="options">
        <.input class="inline" field={f[:is_private]} type="checkbox" label={gettext("is private")} />
        <.input class="inline" field={f[:is_unread]} type="checkbox" label={gettext("read later")} />
      </div>
    </fieldset>
    {submit("Submit")}
  <% end %>
</div>